export default {
    attributeGroups: [
        '^#',
        '^:?is$',
        '^v-tooltip$',
        '^v-close-popper$',
        '^v-html$',
        '^v-text$',
        '^v-for$',
        '^v-(if|else-if|else)$',
        '^v-bind$',
        '^v-show$',
        '^v-cloak$',
        '^v-pre$',
        '^v-once$',
        '^:?id$',
        '^:?ref$',
        '^v-model$',
        '^v-model:',
        '^:?to$',
        '^:?key$',
        '^:?class$',
        '^:(?!data-)',
        '^:?data-',
        '$DEFAULT',
        '^@',
    ],
    endOfLine: 'lf',
    htmlWhitespaceSensitivity: 'ignore',
    importOrder: [
        '<THIRD_PARTY_MODULES>',
        '^@/(.*)$',
        '^(.*)/assets/(.*)$',
        '^(.*)/components/(.*)$',
        '^(.*)/services/(.*)$',
        '^(.*)/stores/(.*)$',
        '^(.*)/config/(.*)$',
        '^(.*)/composables/(.*)$',
        '^(.*)/utils/(.*)$',
        '^(.*)/views/(.*)$',
        '^[./]',
    ],
    importOrderSeparation: true,
    importOrderSortSpecifiers: true,
    plugins: ['@trivago/prettier-plugin-sort-imports', 'prettier-plugin-organize-attributes', 'prettier-plugin-tailwindcss'],
    printWidth: 130,
    semi: false,
    singleAttributePerLine: false,
    singleQuote: true,
    tabWidth: 4,
    trailingComma: 'all',
    useTabs: false,
    vueIndentScriptAndStyle: true,
}
